# Generated by Django 3.2.5 on 2021-08-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210816_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='author',
        ),
    ]
