# Generated by Django 3.2.5 on 2021-08-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist_status',
            field=models.CharField(default='', max_length=21),
            preserve_default=False,
        ),
    ]
