# Generated by Django 3.2.5 on 2021-08-16 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_watchlist_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist_users',
            field=models.ManyToManyField(blank=True, related_name='watched_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
