# Generated by Django 3.2.5 on 2021-08-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_watchlist_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(default=90.0),
            preserve_default=False,
        ),
    ]
