# Generated by Django 3.2.5 on 2021-08-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210817_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('CL', 'Closed')], default='AC', max_length=64),
        ),
    ]
