# Generated by Django 3.2.5 on 2021-08-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('FS', 'Fashion'), ('TO', 'Toys'), ('ET', 'Electronics'), ('HM', 'Home'), ('AR', 'Art'), ('JW', 'Jewelry'), ('PT', 'Properties'), ('CT', 'Contracts'), ('MS', 'Miscellaneous')], max_length=2),
        ),
    ]
