# Generated by Django 3.2.5 on 2021-08-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('CL', 'Closed')], default='AC', max_length=2),
        ),
    ]
